### ISSUE TITLE
Fix : Kitchen Display not restoring accidentally close browser 

### ISSUE THREAD

**Issue by sammish** [bailabs/tailorder-kitchen#1]
Kitchen Display not restoring (Order List ) accidentally closed browser

**Comment by sammish** [comment]
@iRaySpace

**Comment by iRaySpace** [comment]
Hello @sammish Can you check this?

**Comment by sammish** [comment]
@iRaySpace not working

**Comment by jiloysss** [comment]
Hello @sammish we cannot determine what exactly is the problem. It is working fine on @iRaySpace side. Can you send a video so we can check on it, maybe we can determine the problem through the video :)
